In [1]:
import pandas as pd
df = pd.read_csv("heights_2.csv")
df.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_8468\3214219007.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

    name  height
0  mohan     1.2
1  maria     2.3
2  sakib     4.9
3    tao     5.1
4  virat     5.2

In [2]:
df.describe()

          height
count  20.000000
mean    8.390000
std     8.782812
min     1.200000
25%     5.350000
50%     5.700000
75%     6.275000
max    40.200000

In [4]:
Q1 = df.height.quantile(0.25) # same as 25% of describe output
Q3 = df.height.quantile(0.75) # same as 75%
Q1, Q3

(5.3500000000000005, 6.275)

In [5]:
IQR = Q3 - Q1
IQR

0.9249999999999998

In [6]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
lower_limit, upper_limit

(3.962500000000001, 7.6625)

In [7]:
# find outliers
df[(df.height>upper_limit) | (df.height<lower_limit)]

     name  height
0   mohan     1.2
1   maria     2.3
17  aamir    14.5
18    ken    23.2
19    Liu    40.2

In [8]:
# remove outliers
df1 = df[(df.height<upper_limit) & (df.height>lower_limit)]
df.shape, df1.shape

((20, 2), (15, 2))

In [9]:
df1.head()

     name  height
2   sakib     4.9
3     tao     5.1
4   virat     5.2
5  khusbu     5.4
6  dmitry     5.5