In [1]:
"""Pandas lubary
Useful for data processing and analysis
Pandas Data Frame
Pandas DataFrame is two-dimentional tabular data structure with labled axes (rows nd columns)
"""

'Pandas lubary\nUseful for data processing and analysis\nPandas Data Frame\nPandas DataFrame is two-dimentional tabular data structure with labled axes (rows nd columns)\n'

In [19]:
import pandas as pd
import numpy as np

In [5]:
# importing california housing 
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [6]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. topic:: References\n\n    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n      Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [8]:
californa_df = pd.DataFrame(housing.data, columns=housing.feature_names)
californa_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [9]:
californa_df.shape

(20640, 8)

In [11]:
# importing the data from a csv file to a pandas dataframe
diabetics_data = pd.read_csv("diabetes.csv")
diabetics_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
diabetics_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
# loading data from a ecxcel file to a pandas dataframe
data_excell = pd.read_excel("test.xlsx")

In [14]:
# Exporting a pandas dataframe to a csv file
californa_df.to_csv("california.csv")

In [18]:
# exporting a pandas dataframe to en excell file
# californa_df.to_excel("test.xls")
# Need to install xlsx engine

In [22]:
# create dataframe with random values
random_df = pd.DataFrame(np.random.randint(1,100,(20,10)))
random_df.head()

    0   1   2   3   4   5   6   7   8   9
0  64  90  19  65  78  31  34  81  70  31
1  80  38  41   7  10  65  44   7  17  24
2  74  27  14  94  98  18  68  46  79   7
3  31  31  43   7  39  47  47  56  31  82
4  35  54  56  24  20  57  53  53  84  33

In [23]:
random_df.shape

(20, 10)

In [24]:
random_df.describe()

,0,1,2,3,4,5,6,7,8,9
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,56.70000,37.450000,55.950000,42.300000,43.350000,49.700000,53.850000,48.950000,63.200000,49.100000
std,30.00193,27.728904,28.160209,32.825055,26.915609,27.909817,24.694502,24.427067,29.703092,27.447366
min,3.00000,3.000000,1.000000,1.000000,3.000000,1.000000,1.000000,4.000000,3.000000,4.000000
25%,34.00000,17.000000,36.500000,11.000000,25.250000,32.500000,39.250000,30.000000,40.750000,29.250000
50%,63.50000,29.000000,58.000000,38.500000,38.000000,50.000000,58.500000,49.500000,77.000000,52.500000
75%,78.50000,54.000000,79.500000,69.500000,61.000000,70.250000,70.000000,68.500000,84.250000,71.000000
max,98.00000,94.000000,97.000000,94.000000,98.000000,94.000000,93.000000,85.000000,97.000000,84.000000

In [26]:
# last 5 rows of dataframe
random_df.tail()

     0   1   2   3   4   5   6   7   8   9
15  65  26  48  94  63  94  37  60  96  81
16  27   3  95  42  36  33  77  37  76  12
17   3  54  60  50  59  90  80  19  54  46
18  78  25  30   1  26  70  31  27  92  84
19   4  21   1  86  61  36   1  47  82  50

In [27]:
random_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     int64
 1   1       20 non-null     int64
 2   2       20 non-null     int64
 3   3       20 non-null     int64
 4   4       20 non-null     int64
 5   5       20 non-null     int64
 6   6       20 non-null     int64
 7   7       20 non-null     int64
 8   8       20 non-null     int64
 9   9       20 non-null     int64
dtypes: int64(10)
memory usage: 1.7 KB

In [30]:
# finding the number of missing values
californa_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [31]:
diabetes_df = diabetics_data

In [32]:
diabetes_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [33]:
diabetes_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [35]:
# counting the values based on labels
diabetes_df.value_counts("Outcome")

Outcome
0    500
1    268
Name: count, dtype: int64

In [38]:
# group the values based on the mean
diabetes_df.groupby("Outcome").mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [39]:
# Statistical Measures
# count or number of values
californa_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [40]:
# Mean value column wise
californa_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [41]:
# standard deviation - column wise
californa_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [42]:
# minimum value column wise
californa_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [43]:
# maximum value column wise
californa_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [44]:
# Median column wise
californa_df.median()

MedInc           3.534800
HouseAge        29.000000
AveRooms         5.229129
AveBedrms        1.048780
Population    1166.000000
AveOccup         2.818116
Latitude        34.260000
Longitude     -118.490000
dtype: float64

In [45]:
# Mode column wise
californa_df.mode()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,3.1250,52.0,5.0,1.0,891.0,3.0,34.06,-118.31
1,15.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
californa_df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [61]:
# Manipulating dataframe
# adding a column to a dataframe
californa_df["target"] = housing.target

ValueError: Length of values (20640) does not match length of index (20639)

In [51]:
californa_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [54]:
# Removing a row
californa_df.drop(index=0, axis=0, inplace=True)
californa_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [57]:
# removing a column
californa_df.drop(columns="target", axis=1, inplace=True) # inplace true delete permantly
californa_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [62]:
# get the third row by index
californa_df.iloc[2]

MedInc          5.643100
HouseAge       52.000000
AveRooms        5.817352
AveBedrms       1.073059
Population    558.000000
AveOccup        2.547945
Latitude       37.850000
Longitude    -122.250000
Name: 3, dtype: float64

In [64]:
# locating a particular column
print(californa_df.iloc[:,0]) # first column
print(californa_df.iloc[:,1]) # scoond column
print(californa_df.iloc[:,2]) # third column
print(californa_df.iloc[:,-1]) # last column

1        8.3014
2        7.2574
3        5.6431
4        3.8462
5        4.0368
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20639, dtype: float64
1        21.0
2        52.0
3        52.0
4        52.0
5        52.0
         ...
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20639, dtype: float64
1        6.238137
2        8.288136
3        5.817352
4        6.281853
5        4.761658
           ...
20635    5.045455
20636    6.114035
20637    5.205543
20638    5.329513
20639    5.254717
Name: AveRooms, Length: 20639, dtype: float64
1       -122.22
2       -122.24
3       -122.25
4       -122.25
5       -122.25
          ...
20635   -121.09
20636   -121.21
20637   -121.22
20638   -121.32
20639   -121.24
Name: Longitude, Length: 20639, dtype: float64

In [65]:
# correlation
# positive correlation
# negetive correlation
californa_df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
MedInc,1.000000,-0.119164,0.326871,-0.062031,0.004946,0.018774,-0.079941,-0.015028
HouseAge,-0.119164,1.000000,-0.153312,-0.077742,-0.296212,0.013194,0.011123,-0.108141
AveRooms,0.326871,-0.153312,1.000000,0.847635,-0.072186,-0.004851,0.106361,-0.027501
AveBedrms,-0.062031,-0.077742,0.847635,1.000000,-0.066206,-0.006182,0.069731,0.013335
Population,0.004946,-0.296212,-0.072186,-0.066206,1.000000,0.069862,-0.108740,0.099717
AveOccup,0.018774,0.013194,-0.004851,-0.006182,0.069862,1.000000,0.002369,0.002473
Latitude,-0.079941,0.011123,0.106361,0.069731,-0.108740,0.002369,1.000000,-0.924661
Longitude,-0.015028,-0.108141,-0.027501,0.013335,0.099717,0.002473,-0.924661,1.000000