In [41]:
# importing the dependent modules
import pandas as pd
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [49]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [50]:
df.shape

(891, 12)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [52]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [53]:
# df["Sex"] = df["Sex"].map({"male": 1, "female": 2})
df.Sex.isnull().sum()

0

In [55]:
# Taking the necessary columns and removeing p id name sibsp parch ticket cabon and embarked
inputs = df.drop(["PassengerId", "Name", "SibSp", "Parch", "Cabin","Ticket", "Embarked", "Survived"], axis="columns")
target = df.Survived

In [56]:
inputs.Age.isnull().sum()

177

In [57]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [58]:
inputs.Age.isnull().sum()

0

In [59]:
inputs.Sex = inputs.Sex.map({"male": 1, "female": 2})

In [60]:
inputs.Sex

0      1
1      2
2      2
3      2
4      1
      ..
886    1
887    2
888    2
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [61]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [74]:
# Splitting the value into trin and test
X_train, X_test, Y_train, Y_test = train_test_split(inputs, target, test_size=0.1, stratify=target, random_state=2)

In [75]:
inputs.shape, X_train.shape, X_test.shape

((891, 4), (801, 4), (90, 4))

In [76]:
model = tree.DecisionTreeClassifier()

In [77]:
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [78]:
model.score(X_train, Y_train)

0.982521847690387

In [79]:
model.score(X_test, Y_test)

0.8